### ISSUE TITLE
礼貌催更 - 主页点击图标或者快捷键实现打开/关闭

### ISSUE THREAD

**Issue by windy1021** [Lukoning/PiPWindow#1]
很好用的小窗，希望可以尽早实现在主页直接点击图标或者快捷键来实现打开/关闭

**Comment by Lukoning** [comment]
> 很好用的小窗，希望可以尽早实现在主页直接点击图标或者快捷键来实现打开/关闭

收到，国庆整

**Comment by Lukoning** [comment]
已更新：https://github.com/Lukoning/PiPWindow/releases/tag/v0.1.0
