### ISSUE TITLE
优化建议 - 自动最小化、还原主窗口

### ISSUE THREAD

**Issue by windy1021** [Lukoning/PiPWindow#2]
如果点击❤️旁边的小窗可以自动最小化或者关闭窗口感觉会更好？然后点击小窗的返回可以自动打开窗口？

感谢更新，希望可以早日实现小窗控制播放❤️

**Comment by Lukoning** [comment]
> 如果点击❤️旁边的小窗可以自动最小化或者关闭窗口感觉会更好？然后点击小窗的返回可以自动打开窗口？
> 
> 感谢更新，希望可以早日实现小窗控制播放❤️

好好，真成另一个mini模式了是吧（）

目前可以通过同时使用mini模式，来解决歌曲播放控制的问题，像这样：
![image](https://github.com/user-attachments/assets/8e297f80-3117-498f-8842-cf19dffcfac3)

**Comment by windy1021** [comment]
> > 如果点击❤️旁边的小窗可以自动最小化或者关闭窗口感觉会更好？然后点击小窗的返回可以自动打开窗口？
> > 感谢更新，希望可以早日实现小窗控制播放❤️
> 
> 好好，真成另一个mini模式了是吧（）
> 
> 目前可以通过同时使用mini模式，来解决歌曲播放控制的问题，像这样： ![image](https://private-user-images.githubusercontent.com/92252063/373016462-8e297f80-3117-498f-8842-cf19dffcfac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjU3MzAsIm5iZiI6MTcyNzk2NTQzMCwicGF0aCI6Ii85MjI1MjA2My8zNzMwMTY0NjItOGUyOTdmODAtMzExNy00OThmLTg4NDItY2YxOWRmZmNmYWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDE0MjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNGQ0OWNhNDk3YzFmOTg0MGQ0NWZjZGVmMjQyODRjNDhmYTgzN2QwMDAwMDU0NWZiNTY2ZTJlN2FiNTA2NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PS2168wxH0_05lmZ_YMJDVcq4WMOLBEWdIhdJYCuzK0)

早日取代mimi模式哈哈哈

**Comment by Lukoning** [comment]
v0.2.0更新 已实现此功能

**Comment by windy1021** [comment]
> v0.2.0更新 已实现此功能

辛苦😍😍😍感觉很完美，可以改名叫better mini了哈哈
