### ISSUE TITLE
更多分辨率选项、小窗按钮BUG反馈、单独设置日文歌词字体

### ISSUE THREAD

**Issue by Mascot-N** [Lukoning/PiPWindow#4]
1：2160×1440的屏幕，分辨率自适应很糊，改到1080p有锯齿感，希望添加2k和4k的选项。
2：暂停时鼠标悬停底部会只有返回键，同时即使有设置，此时关闭仍然会回到主页面。
3：如果日文歌歌词的字体可以单独设置，我感激不尽！（）

**Comment by Lukoning** [comment]
1. 有锯齿感说明渲染分辨率太高了（作为参考，1080p的屏幕只能把小窗拉到最高480p，这么大：
![image](https://github.com/user-attachments/assets/e8e3a519-a524-4bb6-ad0f-b35897424312)
），考虑下个版本增加1080p~480p的过渡选项
2. 介个是已知问题……
3. 考虑以后加入

**Comment by Lukoning** [comment]
1. v0.2.2已经加了，如有需要也可以自行修改配置文件然后重载：
F12 -> Application -> 展开Local Storage -> orpheus://orpheus -> Filter搜索pip -> 找到PiPWindowSettings -> 修改图中数值
![image](https://github.com/user-attachments/assets/6c1ea488-da69-4a54-b2ad-dfd7ceddd391)
2. 不行啊什么办法都试过了没点有用的
3. 另立一个issue #5
