### ISSUE TITLE
关于歌词加粗原文

### ISSUE THREAD

**Issue by Mascot-N** [Lukoning/PiPWindow#7]
如果和RefinedNowPlaying和LyricBar一样可以关闭加粗原文就好了

**Comment by Lukoning** [comment]
实现功能不难…可惜电脑不在手，下周再看咯

也可以自己摸索源代码，把加粗改掉（?）

**Comment by Lukoning** [comment]
已更新 https://github.com/Lukoning/PiPWindow/releases/tag/v0.2.3
